package exception;

import java.util.InputMismatchException;
import java.util.Scanner;

public class ExceptionThrowsTest  {

	public static void main(String[] args) throws InputMismatchException {
//		getPositiveNumber();
		System.out.print("숫자를 입력하세요 >>>>");
		int num = 0;
		try {
			num = getPositiveNumber();
			System.out.println("값은 : " + num);
		} catch (InputMismatchException e) {
			// TODO Auto-generated catch block
//			e.printStackTrace();
			System.out.println("숫자가 아닙니다");
		}
		

		System.out.println("문자열을 입력하세요");
		Scanner sc = new Scanner (System.in);
		String str = sc.nextLine();
		
		int num2 = Integer.parseInt(str);
		System.out.println("값은 : " + num2);
		
		
		
//		num = getPositiveNumber();
//		System.out.println("값은 : " + num);

	}

	private static int getPositiveNumber() throws InputMismatchException {
		Scanner sc = new Scanner (System.in);
		int tmp = sc.nextInt();
		
		return tmp;
	}
}
